name: Testing Environments

on:
    push:
        branches:
            - 'feature/**'

jobs:
    deploy:
        if: ${{ contains(github.event.head_commit.message, '[devdeploy]') }} 
        name: Deploy Dev
        runs-on: ubuntu-latest
        environment: DEV
    
        steps:
            - name: Echo env variable
              run: echo ${{ vars.TEST_DEV }}